model:
  type: gru
  input_size: 38  # Number of features (4 pain surveys + 3 subject chars + 31 joints)
  hidden_size: 128
  num_layers: 2
  num_classes: 3
  dropout: 0.3
  bidirectional: True

data:
  train_path: data/train_data/pirate_pain_train.csv
  labels_path: data/train_data/pirate_pain_train_labels.csv
  test_path: data/test_data/pirate_pain_test.csv
  seq_length: 160
  val_split: 0.2
  normalize: True
  Missing_value_strategy: mean
  Augmentation: True
  Augmentation_noise_level: 0.01

training:
  batch_size: 16
  num_epochs: 100
  learning_rate: 0.001
  weight_decay: 0.001
  early_stopping_patience: 10
  num_workers: 0  # Set to 0 for Windows compatibility
  seed: 42
